@extends('layout')
@section('title', 'Keranjang Belanja')
@section('page', 'keranjang')
@section('content')
    <div class="cart-heading"><div><a class="back-link" href="{{ route('katalog') }}">← Kembali ke daftar barang</a><h1>Keranjang belanja<span>.</span></h1><p>Pilihanmu, siap menemani ide berikutnya.</p></div><span class="pill"><span aria-hidden="true">●</span> Tanpa login</span></div>
    <section class="empty-cart" id="empty-cart"><div class="empty-illustration" aria-hidden="true"><svg viewBox="0 0 100 100" fill="none"><path d="M22 33h56l-5 47H27z" fill="#DDE8DF" stroke="#356763" stroke-width="2"/><path d="M36 36v-8a14 14 0 0 1 28 0v8" stroke="#356763" stroke-width="2.5"/><path d="M40 53h20M50 43v20" stroke="#356763" stroke-width="2.5" stroke-linecap="round"/></svg></div><span class="eyebrow">MASIH ADA RUANG UNTUK IDE</span><h2>Keranjangmu masih kosong</h2><p>Mulai dengan buku baru atau pulpen favorit.<br>Tambahkan barang yang kamu butuhkan.</p><a href="{{ route('katalog') }}" class="primary-button">Jelajahi daftar barang <span aria-hidden="true">→</span></a></section>
    <section id="filled-cart" class="cart-layout" hidden>
        <div><div class="items-label"><h2>Barang pilihanmu</h2><span id="item-summary"></span></div><div id="cart-items" class="cart-items"></div><button class="clear-button" id="clear-cart">Kosongkan keranjang</button></div>
        <aside class="order-summary"><span class="eyebrow">SEMUA PILIHANMU</span><h2>Ringkasan belanja</h2><div class="summary-line"><span>Jumlah barang</span><strong id="summary-count">0 item</strong></div><div class="summary-line"><span>Subtotal barang</span><strong id="summary-subtotal">Rp 0</strong></div><div class="summary-total"><span>Total</span><strong id="summary-total">Rp 0</strong></div><a class="primary-button" href="{{ route('katalog') }}">Tambah barang lagi <span aria-hidden="true">+</span></a><p class="summary-note">Pilihan tersimpan di browser ini.<br>Jumlah dibatasi sesuai stok produk.</p></aside>
    </section>
    <template id="cart-item-template"><article class="cart-item"><div class="cart-item-art"></div><div class="cart-item-detail"><h3></h3><p class="item-price"></p><span class="item-stock"></span><button class="remove-button" type="button">Hapus</button></div><div class="cart-item-actions"><div class="quantity-control"><button type="button" data-action="decrement" aria-label="Kurangi jumlah">−</button><span class="quantity"></span><button type="button" data-action="increment" aria-label="Tambah jumlah">+</button></div><strong class="item-subtotal"></strong></div></article></template>
    <div hidden id="product-art-library">@foreach($barang as $item)<div data-art="{{ $item->id }}"><x-product-art :id="$item->id" /></div>@endforeach</div>
@endsection
