@extends('layout')
@section('title', 'Keranjang Belanja')
@section('content')
<div class="page-heading"><div><span class="eyebrow">SATU LANGKAH MENUJU IDE BARU</span><h1>Keranjang belanja</h1><p>{{ $items->count() }} jenis barang pilihanmu. Periksa kembali sebelum checkout.</p></div><a class="text-link" href="{{ route('products') }}">← Lanjut belanja</a></div>
@if($items->isEmpty())
<section class="empty-state"><span class="empty-symbol" aria-hidden="true">＋</span><h2>Keranjangmu masih kosong</h2><p>Ada banyak perlengkapan untuk menemani ide berikutnya.</p><a class="button" href="{{ route('products') }}">Jelajahi katalog <span aria-hidden="true">→</span></a></section>
@else
<div class="cart-layout"><section class="cart-list" aria-label="Daftar barang dalam keranjang"><div class="table-labels"><span>BARANG PILIHAN</span><span>JUMLAH</span><span>SUBTOTAL</span></div>
    @foreach($items as $item)
    <article class="cart-item"><div class="cart-product"><img src="{{ asset('images/'.$item->gambar) }}" alt="{{ $item->nama_barang }}" width="104" height="85"><div><span class="product-code">{{ $item->id_barang }}</span><h3>{{ $item->nama_barang }}</h3><p>Rp{{ number_format((float)$item->harga, 0, ',', '.') }} / barang</p><span class="stock-text {{ $item->jumlah > $item->stok ? 'danger' : '' }}">Stok tersedia: {{ $item->stok }}</span></div></div><form class="quantity-form" method="POST" action="{{ route('cart.update', $item->id_barang) }}">@csrf @method('PATCH')<label class="sr-only" for="qty-{{ $item->id_barang }}">Jumlah {{ $item->nama_barang }}</label><input id="qty-{{ $item->id_barang }}" name="jumlah" type="number" value="{{ $item->jumlah }}" min="0" max="{{ $item->stok }}" required><button type="submit">Ubah</button></form><div class="cart-subtotal"><strong>Rp{{ number_format((float)$item->harga * $item->jumlah, 0, ',', '.') }}</strong><form method="POST" action="{{ route('cart.remove', $item->id_barang) }}">@csrf @method('DELETE')<button class="remove-button" type="submit" aria-label="Hapus {{ $item->nama_barang }}">Hapus</button></form></div></article>
    @endforeach
    <p class="cart-help">Ubah jumlah menjadi 0 atau pilih Hapus untuk mengeluarkan barang.</p>
</section><aside class="checkout-panel"><span class="eyebrow">RINGKASAN BELANJA</span><h2>Siap dikirim untukmu.</h2><dl class="totals"><div><dt>Total barang</dt><dd>{{ $items->sum('jumlah') }} buah</dd></div><div><dt>Subtotal</dt><dd>Rp{{ number_format($total, 0, ',', '.') }}</dd></div><div><dt>Ongkos kirim</dt><dd>Rp0</dd></div><div class="grand-total"><dt>Total bayar</dt><dd>Rp{{ number_format($total, 0, ',', '.') }}</dd></div></dl><form class="form checkout-form" method="POST" action="{{ route('checkout') }}">@csrf<input type="hidden" name="checkout_token" value="{{ session('checkout_token') }}"><label for="alamat_pengiriman">Alamat pengiriman</label><textarea id="alamat_pengiriman" name="alamat_pengiriman" rows="3" minlength="10" maxlength="1000" required>{{ old('alamat_pengiriman', auth()->user()->alamat) }}</textarea><button class="button" type="submit">Checkout sekarang <span aria-hidden="true">→</span></button></form><p class="checkout-note">Pastikan jumlah dan alamat sudah benar. Stok akan diperiksa kembali saat checkout.</p></aside></div>
@endif
@endsection
