const {chromium}=require('./playwright-runtime.cjs');
const assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path'),{execFileSync}=require('node:child_process');
const root=path.resolve(__dirname,'..'),shots=path.join(root,'evidence/screenshots'),base='http://127.0.0.1:8003';
const result={date:new Date().toISOString(),steps:[]};let browser;
const db=()=>{execFileSync(path.join(root,'.runtime/php/php.exe'),[path.join(root,'scripts/export-evidence.php')]);return JSON.parse(require('node:fs').readFileSync(path.join(root,'evidence/database-snapshot.json')));};
async function test(name,fn){try{const detail=await fn();result.steps.push({name,passed:true,...detail});console.log('PASS',name);}catch(e){result.steps.push({name,passed:false,error:e.message});throw e;}}
async function shot(p,name){await p.screenshot({path:path.join(shots,name+'.png'),fullPage:true});}
(async()=>{await fs.mkdir(shots,{recursive:true});browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});const c=await browser.newContext({viewport:{width:1366,height:900}}),p=await c.newPage();
await test('Katalog publik sepuluh produk dan stok habis',async()=>{await p.goto(base,{waitUntil:'networkidle'});assert.equal(await p.locator('.product-card').count(),10);await shot(p,'toko-katalog');await p.goto(base+'/keranjang');assert.equal(p.url(),base+'/login');await shot(p,'toko-login');});
await test('Login Budi dan mengisi keranjang',async()=>{await p.locator('#username').fill('budi');await p.locator('#password').fill('rahasia123');await p.getByRole('button',{name:/Masuk/}).click();await p.waitForLoadState('networkidle');await p.goto(base);for(const id of ['B001','B001','B002','B002','B002']){await p.locator('form[action="'+base+'/keranjang/'+id+'"] button').click();await p.waitForLoadState('networkidle');}await p.goto(base+'/keranjang');assert.match(await p.locator('.grand-total').innerText(),/19.000/);await shot(p,'toko-keranjang');result.before=db();assert.equal(result.before.queries.products.rows.find(r=>r.id_barang==='B001').stok,40);});
let orderId;
await test('Checkout pesanan detail stok dan cart atomik',async()=>{await p.locator('#alamat_pengiriman').fill('Jalan Belajar No. 12, Bandung (alamat demo)');await p.getByRole('button',{name:/Checkout sekarang/}).click();await p.waitForURL('**/pesanan/*');orderId=p.url().split('/').pop();assert.match(await p.locator('body').innerText(),/19.000/);await shot(p,'toko-checkout-berhasil');const after=db();result.after=after;const order=after.queries.orders.rows.find(r=>r.id_order===orderId);assert.equal(Number(order.total_harga),19000);assert.equal(after.queries.details.rows.filter(r=>r.id_order===orderId).length,2);assert.equal(after.queries.products.rows.find(r=>r.id_barang==='B001').stok,38);assert.equal(after.queries.products.rows.find(r=>r.id_barang==='B002').stok,57);assert.equal(after.queries.cart.rows.filter(r=>r.id_user==='U001').length,0);return{orderId,total:19000,bookStock:[40,38],penStock:[60,57],detailCount:2,cartAfter:0};});
await test('Riwayat dan keranjang kosong sesudah checkout',async()=>{await p.goto(base+'/keranjang');assert.match(await p.locator('body').innerText(),/Keranjangmu masih kosong/);await shot(p,'toko-keranjang-setelah-checkout');await p.goto(base+'/pesanan');assert.match(await p.locator('body').innerText(),new RegExp(orderId));await shot(p,'toko-riwayat');});
await test('Pesanan akun lain tidak dapat dibuka',async()=>{await p.getByRole('button',{name:/Logout/}).click();await p.waitForLoadState('networkidle');await p.locator('#username').fill('siti');await p.locator('#password').fill('rahasia123');await p.getByRole('button',{name:/Masuk/}).click();await p.waitForLoadState('networkidle');const response=await p.goto(base+'/pesanan/'+orderId);assert.equal(response.status(),404);await shot(p,'toko-akses-pesanan-ditolak');return{otherUser:'siti',status:404};});
await test('Bukti tabel users hash dan hasil database',async()=>{await p.goto('http://127.0.0.1:8004/evidence/database-snapshot.html');await p.locator('#users').screenshot({path:path.join(shots,'t1-tabel-users.png')});await shot(p,'toko-database-sesudah');});
await c.close();})().catch(e=>{result.error=e.stack;process.exitCode=1;console.error(e);}).finally(async()=>{await browser?.close();await fs.writeFile(path.join(root,'evidence/shop-browser.json'),JSON.stringify(result,null,2));});
